CREATE TABLE "MEAL" (
    "IDX" NUMBER NOT NULL, 
    "NAME" VARCHAR2(20) NOT NULL, 
    "SUBJECT" VARCHAR2(30) NOT NULL, 
    "CONTENT" VARCHAR2(100) NOT NULL, 
    "FILENAME" VARCHAR2(70), 
    "WRITEDATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL,
    "CNUM" NUMBER, 
    CONSTRAINT "FK_CNUM_MAIN_TO_MEAL" FOREIGN KEY ("CNUM")
    REFERENCES "MAIN" ("CNUM")
);

DROP TABLE MEAL;

DELETE FROM MEAL;
DROP SEQUENCE meal_idx_seq;
create sequence meal_idx_seq;

select * from meal;

commit;