CREATE TABLE "SCHEDULE" (	
    "SCHEDULE_IDX" NUMBER(*,0) NOT NULL, 
    "SCHEDULE_NUM" NUMBER(*,0), 
    "SCHEDULE_SUBJECT" VARCHAR2(100), 
    "SCHEDULE_DESC" VARCHAR2(300), 
    "SCHEDULE_DATE" DATE DEFAULT sysdate,
    CONSTRAINT "PK_SCHEDULE_IDX" PRIMARY KEY ("SCHEDULE_IDX")
);

DROP TABLE SCHEDULE;

DELETE FROM SCHEDULE;
DROP SEQUENCE SCHEDULE_idx_seq;
CREATE SEQUENCE SCHEDULE_idx_seq;

SELECT * FROM SCHEDULE ORDER BY SCHEDULE_NUM DESC;
SELECT COUNT(*) FROM SCHEDULE;

COMMIT;
